//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_STATUS
    {
        public int LOGIN_STATUS_ID { get; set; }
        public int LOGIN_STATUS_VALUE { get; set; }
    }
}
