//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_CUSTOMER
    {
        public int CUSTOMER_ID { get; set; }
        public int CUSTOMER_STATEMENT_STATUS { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string CUSTOMER_SUB_DISTRICT { get; set; }
        public string CUSTOMER_DISTRICT { get; set; }
        public string CUSTOMER_PROVINCE { get; set; }
        public string CUSTOMER_POSTCODE { get; set; }
        public string CUSTOMER_TEL_NO { get; set; }
        public string CUSTOMER_FAX { get; set; }
    }
}
