//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DESTINATION
    {
        public string DESTINATION_ID { get; set; }
        public string DESTINATION_NAME { get; set; }
        public string DESTINATION_ADDRESS { get; set; }
        public Nullable<int> DESTINATION_DISTRICT { get; set; }
        public Nullable<int> DESTINATION_AMPHURE { get; set; }
        public Nullable<int> DESTINATION_PROVINCE { get; set; }
        public string DESTINATION_POSTCODE { get; set; }
        public string DESTINATION_TEL_NO { get; set; }
        public string DESTINATION_FAX { get; set; }
    }
}
