//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DATA_BASIC
    {
        public int BASIC_ID { get; set; }
        public Nullable<int> BASIC_CARD_NO { get; set; }
        public Nullable<int> BASIC_CARD_NO_SCOOP { get; set; }
        public Nullable<int> BASIC_RECEIPT_NO { get; set; }
        public Nullable<int> BASIC_DECIMAL { get; set; }
        public Nullable<int> BASIC_MOVE_NO { get; set; }
        public Nullable<int> BASIC_DEDUCTION { get; set; }
        public Nullable<int> BASIC_FARE { get; set; }
        public Nullable<int> BASIC_STATUS_PRINT_CARD_NO { get; set; }
        public Nullable<int> BASIC_STATUS_PRINT_CARD_SEND { get; set; }
        public Nullable<int> BASIC_STATIS_SHOW_CARD_FARE { get; set; }
        public Nullable<int> BASIC_STATUS_PRINT_OUTLOOK_VENDOR { get; set; }
    }
}
