//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_MENU
    {
        public int MENU_ID { get; set; }
        public string MENU_CODE { get; set; }
        public string MENU_NAME_TH { get; set; }
        public string MENU_NAME_EN { get; set; }
        public int STATUS_FLAG { get; set; }
        public string CREATE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
