//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DISTRICTS
    {
        public int DISTRICT_ID { get; set; }
        public Nullable<int> ZIP_CODE { get; set; }
        public string NAME_TH { get; set; }
        public string NAME_EN { get; set; }
        public Nullable<int> AMPHURE_ID { get; set; }
    }
}
