//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DISTINATION
    {
        public long DISTINATION_ID { get; set; }
        public string DISTINATION_NAME { get; set; }
        public string DISTINATION_ADDRESS { get; set; }
        public string DISTINATION_DISTRICT_ONE { get; set; }
        public string DISTINATION_DISTRICT_TWO { get; set; }
        public string DISTINATION_COUNTY { get; set; }
        public string DISTINATION_POSTCODE { get; set; }
        public string DISTINATION_TEL_NO { get; set; }
        public string DISTINATION_FAX { get; set; }
    }
}
