//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DATA_BASIC
    {
        public long BASIC_ID { get; set; }
        public Nullable<int> BASIC_CARD_NO { get; set; }
        public Nullable<int> BASIC_RECEIPT_NO { get; set; }
        public Nullable<int> BASIC_DECIMAL_NUMBER { get; set; }
        public Nullable<int> BASIC_MOVE_NO { get; set; }
        public Nullable<int> BASIC_DEDUCTION { get; set; }
        public Nullable<int> BASIC_FARE { get; set; }
        public Nullable<int> BASIC_STATUS_SCALE_CARD { get; set; }
        public Nullable<int> BASIC_STATUS_BALANCE { get; set; }
        public Nullable<int> BASIC_STATUS_CUSTOMER { get; set; }
    }
}
