//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_MOISTURE
    {
        public long MOISTURE_ID { get; set; }
        public Nullable<int> MOISTURE_MOISTURE { get; set; }
        public Nullable<int> MOISTURE_LESS_HUMIDITY { get; set; }
        public Nullable<int> MOISTURE_DIVIDER { get; set; }
    }
}
