//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_BUSINESS
    {
        public long BUSINESS_ID { get; set; }
        public string BUSINESS_NAME { get; set; }
        public string BUSINESS_ADDRESS { get; set; }
        public string BUSINESS_TEL_NO { get; set; }
    }
}
