//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_CUSTOMER_SERVICE
    {
        public int CUSTOMER_SERVICE_ID { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int SERVICE_CHARGE_ID { get; set; }
    }
}
