//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DESTINATION
    {
        public string DESTINATION_ID { get; set; }
        public string DESTINATION_NAME { get; set; }
        public string DESTINATION_ADDRESS { get; set; }
        public string DESTINATION_DISTRICT_ONE { get; set; }
        public string DESTINATION_DISTRICT_TWO { get; set; }
        public string DESTINATION_COUNTY { get; set; }
        public string DESTINATION_POSTCODE { get; set; }
        public string DESTINATION_TEL_NO { get; set; }
        public string DESTINATION_FAX { get; set; }
    }
}
