//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_LINE_DOWN
    {
        public string LINE_DOWN_ID { get; set; }
        public string LINE_DOWN_NAME { get; set; }
        public Nullable<int> LINE_DOWN_CALCULATE { get; set; }
        public Nullable<int> LINE_DOWN_AMOUNT { get; set; }
    }
}
