//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER
    {
        public int REGISTER_ID { get; set; }
        public string REGISTER_MODEL { get; set; }
        public string REGISTER_TYPE { get; set; }
        public string REGISTER_SERIAL_NO { get; set; }
        public string REGISTER_DEVICE_ID { get; set; }
        public string REGISTER_PASSWORD_HASH { get; set; }
        public string REGISTER_CODE { get; set; }
    }
}
