//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STS_SERIAL_PORT
    {
        public int SERIAL_PORT_ID { get; set; }
        public string SERIAL_PORT_PORT_NO { get; set; }
        public int SERIAL_PORT_BAUD_RATE { get; set; }
        public int SERIAL_PORT_DATA_BITS { get; set; }
        public string SERIAL_PORT_STOP_BITS { get; set; }
        public string SERIAL_PORT_PARITY { get; set; }
        public string SERIAL_PORT_HAND_SHAKING { get; set; }
        public Nullable<int> SERIAL_PORT_STATUS_FLAG { get; set; }
    }
}
