//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MST_CUSTOMER
    {
        public int CUSTOMER_ID { get; set; }
        public int CUSTOMER_STATEMENT_STATUS { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string CUSTOMER_SUB_DISTRICT { get; set; }
        public string CUSTOMER_DISTRICT { get; set; }
        public string CUSTOMER_PROVINCE { get; set; }
        public string CUSTOMER_POSTCODE { get; set; }
        public string CUSTOMER_TEL_NO { get; set; }
        public string CUSTOMER_FAX { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_1 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_2 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_3 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_4 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_5 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_6 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_7 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_8 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_9 { get; set; }
        public Nullable<int> CUSTOMER_SERVICE_VALUE_ROW_10 { get; set; }
    }
}
