//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaknampoScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MST_VENDOR
    {
        public string VENDOR_ID { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_ADDRESS { get; set; }
        public string DISTRICT_TH { get; set; }
        public string AMPHURE_TH { get; set; }
        public string PROVINCE_TH { get; set; }
        public string VENDOR_POSTCODE { get; set; }
        public string VENDOR_TEL_NO { get; set; }
        public string VENDOR_FAX { get; set; }
    }
}
