//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeScale.src.model.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MST_CAR_REGISTERTION
    {
        public long CAR_REGISTERTION_ID { get; set; }
        public string CAR_REGISTERTION_NAME { get; set; }
        public Nullable<int> CAR_REGISTERTION_VENDOR_ID { get; set; }
        public string VENDOR_NAME { get; set; }
    }
}
